### PR TITLE
Add a content-security-policy-report-only mode

### PR DESCRIPTION
**Pull request by halostatue**
This is a little more than just supporting `Content-Security-Policy-Report-Only`, but not much.

```
  plug PlugContentSecurityPolicy,
    report_only: true,
    nonces_for: ~w(script_src style_src)a,
    directives: %{
      default_src: :none,
      object_src: :none,
      img_src: :self,
      child_src: :self,
      form_action: :none,
      frame_ancestors: :none,
      script_src: [
        if(Mix.env() == :dev, do: :"unsafe-inline")
      ],
      style_src: [
        :self,
        "https://fonts.googleapis.com",
        if(Mix.env() == :dev, do: :"unsafe-inline")
      ],
      font_src: [
        :self,
        "https://fonts.gstatic.com",
        "data:",
        "https://cdn.jsdelivr.net/semantic-ui/2.2.10/themes/default/assets/fonts/"
      ],
      base_uri: :none,
      report_uri: "https://example.report-uri.com/r/d/csp/wizard"
    }
```

This is how I’m using these changes. I’m also working on a much larger PR that is going to try to do a little more validation of different types as well as explicitly support both CSP Level 2 and CSP Level 3 with options (and validations), but it’s fairly slow going as I’m sort of unhappy with the direction that I’ve taken so far. My push on this started because `:"#{key}_nonce"` is more or less the same as `String.to_atom("#{key}_nonce")`, so I was looking for ways to eliminate dynamic atom creation, amongst other things. I’m stuck on the fact that I don’t actually know CSP, so I’m having to learn a lot and I’m explicitly trying to do level 2 and level 3.

### CODE REVIEW

**Comment by xtian** [comment]
Thanks!

**Comment by xtian** [comment]
Note that I've removed support for atoms in the directives lists. This seems overly magical to me. I'd prefer more of a 1:1 relationship between the user-provided config and the resulting header.

**Comment by halostatue** [comment]
Part of what I’m looking at is that it appears that only `style` and `script` support nonces per the CSP level 2 and level 3 documents. That would make this easier to deal with because then you can always assume `:style_src` and `:script_src`, while ignoring anything else, and not having to support dynamic atom conversion.

**Comment by halostatue** [comment]
I also used `:self` instead of `"'self'"` because it’s fairly awkward to type the latter. No, it isn’t something that needs to be done that frequently, but…

**Comment by xtian** [comment]
Released as v0.2.0. Thanks again!

**Pull request merged**
